sudo: required
language: generic
services:
 - docker
before_install:
 - docker build -t 75017864/docker-react -f Dockerfile.dev .
scripts:
 - docker run 75017864/docker-react:latest npm run test -- --coverage